export const UPDATE_BUTTON = 'UPDATE_BUTTON';
export const ADD_MILESTONES ='ADD_MILESTONES';
export const ADD_MILESTONESSOCIAL ='ADD_MILESTONESSOCIAL';
export const UPDATE_BUTTONSOCIAL = 'UPDATE_BUTTONSOCIAL';